# Generated by Django 5.0.2 on 2025-02-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
